version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: logosph
      POSTGRES_PASSWORD: GygHiA11
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/database
      SPRING_DATASOURCE_USERNAME: logosph
      SPRING_DATASOURCE_PASSWORD: GygHiA11
    ports:
      - "8080:8080"